# Generated by Django 4.1 on 2022-08-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bigoraphy',
            new_name='biography',
        ),
    ]
