# Generated by Django 4.1 on 2022-08-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comenters',
            field=models.CharField(blank='true', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.CharField(blank='true', max_length=255),
        ),
    ]
