# Generated by Django 4.1 on 2022-08-06 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_comenters_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='comenters',
            new_name='description',
        ),
    ]
